default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: homu_development
  username: root

production:
  <<: *default
  host: 127.0.0.1
  database: homu_production
  username: root
  password: <%= ENV['HOMU_DATABASE_PASSWORD'] %>
