default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: homu_development

production:
  <<: *default
  host: 127.0.0.1
  database: homu_production
  username: homu
  password: <%= ENV['HOMU_DATABASE_PASSWORD'] %>
